'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium,_electron}=require('playwright');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'theibs-raise-'));process.env.THEIBS_DATA_PATH=path.join(temp,'events.jsonl');process.env.THEIBS_WORKSPACE_PATH=path.join(temp,'workspace.json');
 const native=process.argv.includes('--electron'),version=require('../package.json').version,out=path.resolve(__dirname,'../../validacao/raise-v'+version);fs.mkdirSync(out,{recursive:true});
 const report={version,environment:native?'PACKAGED_ELECTRON_HTTP':'EDGE_HTTP',checks:[],performance:[],layouts:[],errors:[],status:'RUNNING'};let server,browser,electron,page;
 try{
  if(native){const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;electron=await _electron.launch({executablePath:process.env.THEIBS_EXECUTABLE||path.resolve(__dirname,'../../THEIBS/THEIBS.exe'),args:['--user-data-dir='+path.join(temp,'profile')],env});page=await electron.firstWindow();}
  else{({server}=require('../server'));await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,channel:'msedge'});page=await browser.newPage({viewport:{width:1366,height:768}});await page.goto(`http://127.0.0.1:${server.address().port}`);}
  page.on('pageerror',e=>report.errors.push(e.message));await page.waitForFunction(()=>Boolean(window.theibsApp));await page.evaluate(()=>theibsApp.ready);
  await page.locator('#open-settings').click();await page.locator('#auto-analysis').uncheck();await page.locator('#potBeforeAction').fill('1.5');await page.locator('#amountToCall').fill('1');await page.locator('#samples').selectOption('10000');await page.locator('#settings-dialog [data-close-dialog]').click();
  await page.locator('#variant-select').selectOption('6');await page.locator('#opponent-count').selectOption('2');await page.locator('[data-slot="0"]').click();await page.keyboard.type('aekokeqotc8c');
  const analyze=async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/api/analyze'));await page.locator('#quick-analyze').click();const data=await(await response).json();await page.waitForFunction(()=>!theibsApp.getState().analysisBusy);return data;};
  let result=await analyze();assert.equal(result.ev.comparisonComplete,false);assert.deepEqual(result.ev.missingLegalActions,['RAISE']);assert.notEqual(result.recommendedAction,'RAISE');assert.equal(result.confidence,'LOW');report.checks.push('Missing raise is explicitly partial and cannot be recommended by a heuristic');
  await page.locator('#open-raise-model').click();await page.locator('#study-example').click();await page.locator('#study-contribution-0').fill('0.5');await page.locator('#study-contribution-1').fill('1');await page.locator('#study-min-raise').fill('2');await page.locator('#raiseTo').fill('3.5');await page.locator('#settings-dialog [data-close-dialog]').click();
  result=await analyze();assert.equal(result.status,'NO_DECISION');assert.match(result.reason,/Confirme/);report.checks.push('Response hypotheses require explicit acceptance');
  await page.locator('#open-raise-model').click();await page.locator('#study-accept').check();await page.locator('#settings-dialog [data-close-dialog]').click();result=await analyze();
  assert.equal(result.status,'OK',JSON.stringify(result));assert.equal(result.engineBuild,version);assert.equal(result.ev.comparisonComplete,true);assert.equal(result.ev.actions.RAISE.scenarioBreakdown.length,4);assert.equal(result.scenarioSummary.samplesPerCount,10000);assert.equal(result.scenarioSummary.totalSamples,20000);assert.equal(result.potMath.potAfterCall,3);assert.equal(result.potMath.potOdds,1/3);assert.equal(result.potMath.evCall,result.ev.actions.CALL.ev);
  assert.match(await page.locator('#ev-alternatives').innerText(),/RAISE/);assert.doesNotMatch(await page.locator('#ev-alternatives').innerText(),/—/);report.result=result;report.checks.push('UI produces complete CALL/RAISE scenario EV with consistent 33.3% pot odds');
  for(const [width,height]of [[1366,768],[1024,660]]){await page.setViewportSize({width,height});const s=await page.evaluate(()=>({w:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight}));assert.ok(s.w<=width&&s.h<=height);report.layouts.push({width,height,...s});}
  await page.setViewportSize({width:1366,height:768});await page.screenshot({path:path.join(out,`${native?'electron':'edge'}-raise.png`)});
  await page.locator('#open-analysis').click();await page.locator('.result-disclosure>summary').click();const branch=page.locator('.ev-block details').last();await branch.locator('summary').click();await branch.scrollIntoViewIfNeeded();assert.match(await page.locator('#result').innerText(),/respostas possíveis/);await page.screenshot({path:path.join(out,`${native?'electron':'edge'}-branches.png`)});await page.locator('#analysis-dialog [data-close-dialog]').click();
  await page.evaluate(()=>theibsApp.flushSave());await page.waitForFunction(()=>!theibsApp.getState().saveBusy&&!theibsApp.getState().saveDirty);await page.reload();await page.waitForFunction(()=>Boolean(window.theibsApp));await page.evaluate(()=>theibsApp.ready);assert.equal(await page.locator('#study-mode').inputValue(),'UNIFORM');assert.equal(await page.locator('#study-contribution-0').inputValue(),'0.5');assert.equal(await page.locator('#study-accept').isChecked(),true);report.checks.push('Scenario settings survive restart without overwriting the real user workspace');
  for(let run=1;run<=3;run++){
   const input={variant:'PLO6_HIGH',heroCards:['As','Ks','Qh','Jh','Td','9d'],board:[],players:5,position:'BTN',potBeforeAction:12,amountToCall:4,effectiveStack:100,samples:50000,seed:428+run,unknownOpponentModel:'UNIFORM',assumeNoRake:true};
   const measured=await page.evaluate(async input=>{const started=performance.now(),data=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}).then(r=>r.json());return {data,elapsedMs:performance.now()-started};},input);
   assert.equal(measured.data.status,'OK');report.performance.push({run,samples:measured.data.equity.samples,simulationMs:measured.data.equity.elapsedMs,httpMs:measured.elapsedMs,completeSimulationsPerSecondIncludingRequest:50000000/measured.elapsedMs});
  }
  assert.deepEqual(report.errors,[]);report.status='PASS';
 }catch(error){report.status='FAIL';report.failure=error.stack;if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});throw error;}
 finally{fs.writeFileSync(path.join(out,`${native?'electron':'edge'}-report.json`),JSON.stringify(report,null,2));if(browser)await browser.close();if(electron){try{await electron.evaluate(({app})=>app.exit(0));}catch{}await electron.close();}if(server)await new Promise(r=>server.close(r));}
 console.log(JSON.stringify({status:report.status,checks:report.checks,performance:report.performance},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
